name: Update README.md

on:
  push:
    branches:
      - 'main'

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13' # Specify the Python version

      # Step 3: Install dependencies
      - name: Install mdft
        run: pip install mdft

      # Step 4: Run mdft on README.md
      - name: Process README.md with mdft
        run: |
          python3 -m mdft README.md

      # Step 5: Check for changes
      - name: Check for changes in README.md
        id: check_changes
        run: |
          if [[ -n "$(git status --porcelain)" ]]; then
            echo "README_CHANGED=true" >> $GITHUB_OUTPUT
          else
            echo "README_CHANGED=false" >> $GITHUB_OUTPUT
          fi

      # Step 6: Commit and push changes if README.md has changed
      - name: Commit and push changes
        if: steps.check_changes.outputs.changed == 'true'
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "Updated README.md"
          git push
